### ISSUE TITLE
Test delivery doesn't work due to php7

### ISSUE THREAD

**Issue by bvarnai** [Alroniks/docker-tao#1]
Right after test taker start a test an error is displayed
`Fatal error: Cannot use qtism\common\datatypes\Float as Float because 'Float' is a special class name in /var/www/html/taoQtiTest/helpers/class.TestSession.php on line 31`
It seems  is not yet supported see [https://forge.taotesting.com/boards/6/topics/2804](url). I wonder how to use this container than?

**Comment by alroniks** [comment]
Hi @bvarnai 

Thank you for your interest. Unfortunately, Docker support TAO is currently experimental. However, I use it every day to work with the TAO project.

PHP7 is not officially supported, but I use the TAO with PHP 7.1 and it works fine for me. I remember that we fixed the issues that you describe, but I'm not sure that it was delivered to the latest version. I updated image by the new version (RC7) a few weeks ago, perhaps you used an older version RC3 without support php7.

As it's experimental repository, some changes can be undocumented, but you can find latest instructions how to run TAO in Docker here - https://gist.github.com/Alroniks/4a09104ef35198171e537e29b94bddb4

Please, try run it again. And feel free to ask anything about TAO and Docker.

**Comment by don-smith** [comment]
@Alroniks if you're not experiencing this, I suspect you've done something to your environment that is different from the environment created by the instructions in the README. I'm experiencing the same issue as @bvarnai without any modification.

I appreciate this is experimental, and it has been a huge help to me, but I just though you should know it's currently broken for those of us with fresh environments. Cheers!

**Comment by aroca** [comment]
The same problem here following the actual README

**Comment by aroca** [comment]
Seems like an old issue, but i still see the same problem. Anyone using this? 

Cheers!

**Comment by alroniks** [comment]
Hi @aroca 
Yes, it is an old issue, but actually, TAO platform works with 7.1. But it seems that in the image the old code base. I will check it tomorrow morning and update Dockerfile.

**Comment by aroca** [comment]
Hi @Alroniks how are you? any update on this? I dont want to bother you, but if you need a hand testing or in any way, just shout. Cheers!

**Comment by aroca** [comment]
Tried to build Dockerfile but errors out with some missnaming packages.

```E: Package 'libpng12-dev' has no installation candidate```

Fixed that but it then fails with:

```checking for igbinary includes... configure: error: Cannot find igbinary.h
ERROR: `/tmp/pear/temp/redis/configure --with-php-config=/usr/local/bin/php-config --enable-redis-igbinary=y' failed
The command '/bin/sh -c yes | pecl install redis' returned a non-zero code: 1```

**Comment by aroca** [comment]
Hello! Any news about this? Cheers!

**Comment by aroca** [comment]
If anybody hit this bug, just to let you know that pointing to the latest RC it works.. so just modify that until this is addressed. Cheers
